name: Build Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install the package and dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Build, make LLM friendly and deploy docs
        run: |
          mkdocs build
          llms-txt
          mkdocs gh-deploy --dirty