name: PR Bot

on:
  pull_request:
    types: [opened, closed, reopened, converted_to_draft, ready_for_review]
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  call-reusable-workflow:
    # For issue_comment events, only proceed if the comment contains "/review"
    if: ${{ (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/review')) || github.event_name != 'issue_comment' }}
    uses: lightly-ai/pr-bot/.github/workflows/pr_bot.yml@main
    with:
      slack_channel_id: C01KSD8EE65  # dev-pull-requests
      post_new_message: ${{ github.event_name == 'issue_comment' }}
      repo: ${{ github.repository }}
      # For pull_request events, use github.event.number,
      # for issue_comment events, use github.event.issue.number,
      # and for pull_request_review events, use github.event.pull_request.number.
      pr_number: ${{ github.event.pull_request.number || github.event.issue.number || github.event.number }}
      # If available (only on pull_request_review events), pass the review state and reviewer.
      # (x && y || z) is acting as a ternary operator.
      review_state: ${{ github.event.review && github.event.review.state || '' }}
      reviewer: ${{ github.event.review && github.event.review.user.login || '' }}
    secrets:
      pr_bot_deploy_private_key: ${{ secrets.PR_BOT_DEPLOY_PRIVATE_KEY }}
      caller_github_token: ${{ secrets.github_token }}
      slack_pr_bot_token: ${{ secrets.SLACK_PR_BOT_TOKEN }}